### ISSUE TITLE
不应该删掉 lib/form-select/engine.rb 文件

### ISSUE THREAD

**Issue by piecehealth** [rails-engine/form-select#1]
`ActiveRecord::Base.send(:include, FormSelect::Model)`放到`lib/form-select.rb`会拖慢启动速度，详情见
https://guides.rubyonrails.org/engines.html#what-are-on-load-hooks-questionmark

**Comment by huacnlee** [comment]
https://github.com/rails-engine/form-select/commit/0f49d7732722702273e91d6a1bcbcf09a1dbcac7

已修复
